export const CustomerEvents = {
  ADD_CUSTOMER: 'ADD_CUSTOMER',
  CUSTOMER_LOGIN: 'CUSTOMER_LOGIN',
  CUSTOMER_LOGOUT: 'CUSTOMER_LOGOUT'
};

export const MessageEvent = {
  SHOW_MESSAGE: 'SHOW_MESSAGE',
  RESET_MESSAGE: 'RESET_MESSAGE',
};